### ISSUE TITLE
Adding sciyoshi repo

### ISSUE THREAD

**Issue by StreakyCobra** [BenoitZugmeyer/RustyAdventOfCode#1]
You may want to add a link to sciyoshi repo: https://github.com/sciyoshi/advent-of-rust-2017

Especially as he is currently [fourth](https://adventofcode.com/2017/leaderboard) in the general leaderbord, probably the best rustacean in the competition 😃

**Comment by BenoitZugmeyer** [comment]
That's *really* impressive! thank you.
